[package]
name = "mancala_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29.1"
mancala_board = { path = "../board" }
bank_bird = { path = "../bank_bird" }
once_cell = "1.20.2"
lazy_static = "1.5.0"
